### PR TITLE
Feature/ken

### PR DESCRIPTION
**Pull request by kennkhr**
Please check if the PR fulfills these requirements

- [x] The commit message follows our guidelines
- [x] Pylint and mypy has been run locally and passes
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Feature: Implementation of the player, enemy, item, menu, etc.

Other information:
Trello Task Ticket: https://trello.com/c/NWkvnruo/5-initial-game-development

### CODE REVIEW

**Review by Jonnyboyyyy — COMMENTED** [review]
Good~

**Review by sandeep-selvaraj — APPROVED** [review]
Looks great!

**Review by DivyenduDutta — APPROVED** [review]
reviewed on 13.05.2023

**Review by Jonnyboyyyy — APPROVED** [review]
Good~

**Pull request merged**
